### ISSUE TITLE
Any way to play online?

### ISSUE THREAD

**Issue by dwtompkins** [tuffee88/d3d12ProxyEdrDx11_0#7]
Is there any chance of getting this hack past the AntiCheat to play online co-op?

**Comment by tuffee88** [comment]
Sorry, none that I know off - Easy Anti-Cheat performs an integrity check for the main files at startup so you won't get past that without tinkering with Easy Anti-Cheat. I'm sure there will be ways to get around this (given the rampant cheater problems in the past) so you *might* want to check out the cheater crowd - if the figure out a way around the protection online play should work with this dll, but might also get you banned by FromSoft (as this is sure to be counted as "real cheating") :-)

I'm closing this because it's not something that can be fixed in this project.
